apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: githubrepo
  name: ingress-editor
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]